version: '3'

services:
  mongo:
    image: mongo
    volumes:
      - stasdata:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: stasmo
      MONGO_INITDB_ROOT_PASSWORD: stasmo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8088:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: stasmo
      ME_CONFIG_MONGODB_ADMINPASSWORD: stasmo


volumes:
  stasdata:
